### ISSUE TITLE
DefaultEnv plugin is not available

### ISSUE THREAD

**Issue by evapoorada** [SAP/cf-cli-defaultenv-plugin#2]
Hello everyone,

since this morning, when executing command "cf install-plugin DefaultEnv" the following error is shown:
```
Searching CF-Community for plugin DefaultEnv...
Plugin DefaultEnv not found on disk or in any registered repo.
Use 'cf repo-plugins' to list plugins available in the repos.
FAILED
```

And when executing "cf repo-plugins" to see the list of plugins available, DefaultEnv is not shown in the list. 
Has this plugin been deleted? Is there a problem?
I don't see any update related to this in cf documentation. Is it going to be a new way to set environment variables in BAS?

Thank you in advance.

**Comment by darmiel** [comment]
Hi @evapoorada, this shouldn't be happening! We'll get in touch with the folks at the CF Community Repo and update this issue if we hear anything new.

In the meantime, you can install the plugin manually from the URL. Go to the [latest release](https://github.com/SAP/cf-cli-defaultenv-plugin/releases), copy the link for the binary matching your operating system and install the plugin with the following command:

```console
cf install-plugin https://github.com/SAP/cf-cli-defaultenv-plugin/releases/download/v1.1.1/DefaultEnv.linux64
```

**Comment by darmiel** [comment]
The issue should now be resolved, and you should be able to install the plugin as usual. 
Please let me know if it works for you. 😊 @evapoorada

**Comment by evapoorada** [comment]
Hi @darmiel it's working perfectly now. I appreciate the fast response! Thank you very much! 😄
